In [10]:
import pandas as pd
import pickle

In [12]:
estructura = pd.read_excel('Layout_BHO.xlsx', index_col=0)
display(estructura)

,TR,JB,IN,String,Panel,IN_type,panel_type
0,TR_1,JB_1.1,IN_1.1.1,String_1.1.1.1,panel_1.1.1.1.1,IN1,330
1,TR_1,JB_1.1,IN_1.1.1,String_1.1.1.1,panel_1.1.1.1.2,IN1,330
2,TR_1,JB_1.1,IN_1.1.1,String_1.1.1.1,panel_1.1.1.1.3,IN1,330
3,TR_1,JB_1.1,IN_1.1.1,String_1.1.1.1,panel_1.1.1.1.4,IN1,330
4,TR_1,JB_1.1,IN_1.1.1,String_1.1.1.1,panel_1.1.1.1.5,IN1,330
...,...,...,...,...,...,...,...
82075,TR_8,JB_8.16,IN_8.16.3,String_8.16.3.8,panel_8.16.3.8.26,IN4,335
82076,TR_8,JB_8.16,IN_8.16.3,String_8.16.3.8,panel_8.16.3.8.27,IN4,335
82077,TR_8,JB_8.16,IN_8.16.3,String_8.16.3.8,panel_8.16.3.8.28,IN4,335
82078,TR_8,JB_8.16,IN_8.16.3,String_8.16.3.8,panel_8.16.3.8.29,IN4,335
82079,TR_8,JB_8.16,IN_8.16.3,String_8.16.3.8,panel_8.16.3.8.30,IN4,335

In [20]:
# Extraido de: https://stackoverflow.com/questions/19798112/convert-pandas-dataframe-to-a-nested-dict
def recur_dictify(frame):
    if len(frame.columns) == 1:
        grouped = frame.groupby(frame.columns[0])
        d = {k: [] for k, g in grouped}
        return frame
    
    grouped = frame.groupby(frame.columns[0])
    d = {k: recur_dictify(g.iloc[:,1:]) for k, g in grouped}
    return d


df_tree = estructura[list(estructura.columns)[:5]].copy(deep=True)
dict_tree = recur_dictify(df_tree)

# with open('tree.pickle', 'wb') as handle:
#     pickle.dump(dict_tree, handle, protocol=pickle.HIGHEST_PROTOCOL)

# display(df_tree)

In [9]:
# Extraido de: https://stackoverflow.com/questions/19798112/convert-pandas-dataframe-to-a-nested-dict
def recur_dictify(frame):
    if len(frame.columns) == 1:
        if frame.to_numpy().size == 1:
            return frame.to_numpy()[0]#[0]
        
        return frame.to_numpy()#.squeeze()
    
    grouped = frame.groupby(frame.columns[0])
    d = {k: recur_dictify(g.iloc[:,1:]) for k, g in grouped}
    return d

df_tree = estructura[list(estructura.columns)[:5]].copy(deep=True)

dict_tree = recur_dictify(df_tree)
dict_tree

AttributeError: 'dict' object has no attribute 'columns'